global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "staging-alfred-api"
    scheme: "https"
    metrics_path: "/application_metrics"
    static_configs:
      - targets: ["staging-alfred-api.up.railway.app"]
